### ISSUE TITLE
In `SineActivation`, sizes of param tensor `self.b` and `self.b0` need fixing

### ISSUE THREAD

**Issue by jaredfeng-ca** [ojus1/Time2Vec-PyTorch#3]
When I tried to add a new boolean feature to the toy dataset, the calculation of `v1` and `v2` cannot be done in the `t2v()` function. Then I change the definitions of `self.b` and `self.b0` to:

        self.b = torch.randn(out_features-1)
        self.b0 = torch.randn(1)

Now everything seems to work well again.

**Comment by ojus1** [comment]
Thank you for pointing the bug out.
